config/routes.rb
Rails.application.routes.draw do

  root to: 'customer/homes#top'
   get '/about' => 'customer/homes#about'


  devise_for :admin, skip: [:registrations, :passwords],controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords],  controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }

  #管理者側のルートはurlにadminがつく
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :items
    resources :cart_items
  end

  #顧客側のルートはurlにcustomerがつかない
  scope module: :customer do
    resources :customers, only: [:show, :edit, :update] do
      collection do
        patch 'delete'
        get 'confirm_delete'
      end
    end
    resources :shipping_addresses, only: [:index, :edit ,:create, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :destroy, :update] do
      collection do
        delete :destroy_all
      end
    end
    resources :order_items
    resources :orders do
       collection do
         post :logs
         get :thanx
       end
     end

  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page]).reverse_order
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      @customer.update(status: false)
      flash[:notice] = "You have updated successfully."
      redirect_to admin_customer_path(@customer)
    else
      render "edit"
    end
  end
  

  
  private

  def customer_params
    params.require(:customer).permit(:family_name, :first_name, :kana_family_name, :kana_first_name, :postal_code, :address, :tel, :email)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    # @order = Order.find(params[id])
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  def index
    @cart_items = my_cart
    @total_price = 0
    @total = @cart_items.sum{|cart_item|cart_item.item.tax_out_price.to_i * cart_item.quantity.to_i * 1.1}
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    if my_cart.find_by(item_id: params[:cart_item][:item_id]).present?
			item_in_cart = my_cart.find_by(item_id: params[:cart_item][:item_id])
			item_in_cart.quantity += params[:cart_item][:quantity].to_i
			item_in_cart.save
      flash[:notice] = '商品を追加でカートに入れました。'
      redirect_to cart_items_path
    elsif @cart_item.save
      flash[:notice] = '商品をカートに入れました。'
      redirect_to cart_items_path
    else
      flash[:alert] = '商品の追加に失敗しました。'
      redirect_to item_path(params[:item_id])
    ender_cart_items_path

    end

  end


  def update
    @cart_item = my_cart.find_by(id: params[:id])

    if @cart_item.update(quantity: params[:quantity].to_i)
      flash[:notice] = 'カート内の内容が更新されました'
    else
      flash[:alert] = 'カート内の内容の更新に失敗しました'
    end
    redirect_to request.referer
  end






def destroy

   #@cart_item = CartItem.find(params[:id])

    @cart_item = my_cart.find_by(id: params[:id])

    if @cart_item.destroy
      flash[:notice] = 'カート内の内容が削除されました'
    else
      flash[:alert] = 'カート内の内容の削除に失敗しました'
    end
    redirect_to request.referer

  end

  def destroy_all
    @cart_item = current_customer.cart_items
    @cart_item.destroy_all
    redirect_to cart_items_path
  end


  private

  def my_cart
    current_customer.cart_items
  end

  def cart_item_params
    params.require(:cart_item).permit(:item_id, :quantity)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!

  def edit
    @customer = Customer.find(params[:id])
  end

  def show
     @customer = Customer.find(params[:id])
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customer_path
    else
      render "edit"
    end
  end
  
  def delete
    @customer = current_customer
    @customer.update(status: false)
    reset_session
    flash[:notice] = "Thanyou for using this site ！"
    redirect_to root_path
  end
  
  def confirm_delete
    @customer = current_customer
  end


  private

  def customer_params
    params.require(:customer).permit(:family_name, :first_name, :kana_family_name, :kana_first_name, :postal_code, :address, :tel, :email, :status)
  end

end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController


  def top
    @items = Item.order(created_at: :desc).limit(4)
    
    
  end

  def about
  end
  
  private

  def home_params
    params.require(:home).permit(:name, :tax_out_price, :image)
  end
  
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    #カートに追加するため
    @cart_items = CartItem.new
  end


  private

  def item_params
    params.require(:item).permit(:name, :explanation, :tax_out_price, :image)
  end

end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  # def new
  #   if CartItem.exists?(customer_id: current_customer.id)
  #     @order = Order.new
  #   else
  #     redirect_to items_path
  #   end
  # end

    def new
    @cart = CartItem.all.where(customer: current_customer)
      if @cart.empty?
      redirect_to cart_items_path, notice: 'cart is empty.'
      end

    @order = Order.new
    @shipping_addresses = ShippingAddress.where(customer: current_customer)
    end



  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @order.save

    current_customer.cart_items.each do |cart_item|
      @order_items = OrderItem.new
      @order_items.item_id = cart_item.item_id

      #購入時価格
      @order_items.subprice = cart_item.item.tax_out_price
      @order_items.quantity = cart_item.quantity
      @order_items.order_id = @order.id
      @order_items.save
    end
    current_customer.cart_items.destroy_all
    redirect_to thanx_orders_path
  end

  def logs
    @cart_items = CartItem.all
    @customer = current_customer
    @total_payment = 0

    @cart_items.each do |cart_item|
    @total_payment += ((cart_item.item.tax_out_price * cart_item.quantity) * 1.1).floor
    end

    @order = Order.new(order_params)
    @postage = 600
    @order.total_payment = @total_payment + 600

    if params[:order][:address_number] == "1"
      @order.name = current_customer.family_name + current_customer.first_name
      @order.address = current_customer.address
      @order.postal_code = current_customer.postal_code

    elsif params[:order][:address_number] == "2"
      @address = ShippingAddress.find_by(customer_id: current_customer.id)
      @order.name = @address.name
      @order.address = @address.address
      @order.postal_code = @address.postal_code
    else params[:order][:select_address] = "3"
      @order.name = params[:order][:name]
      @order.address = params[:order][:address]
      @order.postal_code = params[:order][:postal_code]
    end
  end

  def index
    @orders = Order.order(created_at: :desc).page(params[:page]).per(8)
    # @orders = Order.all
    @order = current_customer
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @postage = 600
    @total_payment = 0
    @order_items.each do |order_items|
      @total_payment += ((order_items.item.tax_out_price*order_items.quantity)*1.1).floor
    end
  end

  def thanx
  end


  private

  def order_params
    params.require(:order).permit(:name, :postal_code, :payment_method, :total_payment, :address ,:customer_id, :postage)
  end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected

  def after_sign_in_path_for(resource)
    about_path(resource)
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :kana_family_name, :kana_first_name, :postal_code, :address, :tel])
  end

end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/shipping_addresses_controller.rb
class Customer::ShippingAddressesController < ApplicationController


  def index
    @shipping_address = current_customer.shipping_addresses.new
    @shipping_addresses = current_customer.shipping_addresses.all
  end

  def create
    @shipping_address = current_customer.shipping_addresses.new(shipping_address_params)
    if @shipping_address.save
      redirect_to shipping_addresses_path
    else
      @shipping_addresses = current_customer.shipping_addresses.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @shipping_address.update(shipping_address_params)
      redirect_to customers_shipping_addresses_path
    else
      render 'edit'
    end
  end

  def destroy
    @shipping_address = current_customer.shipping_addresses.find(params[:id])
    @shipping_address.destroy
    redirect_to shipping_addresses_path
  end

  private

  def set_address
    @shipping_address = current_customer.shipping_addresses.find(params[:id])
  end

  def shipping_address_params
    params.require(:shipping_address).permit(:name, :postal_code, :address).merge(customer_id: current_customer.id)
  end


end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/views/customer/orders/index.html.erb
<main>
  <div class="container">
     <div class="row pt-4 mb-4">
       <h4>注文履歴一覧</h4>
     </div>

     <div class="row">
      <table class="table table-bordered bg-light">
        <tr class="background-color">
          <th>注文日</th>
          <th>配送先</th>
          <th>注文商品</th>
          <th>支払金額</th>
          <th>ステータス</th>
          <th>注文詳細</th>
        </tr>

        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
            <td>
              〒<%= order.postal_code %></br>
              <%= order.address %>
              <%= order.name %>
            </td>
            <td>
              <% order.order_items.each do |order_items| %>
                <%= order_items.item.name %>
              <% end %>
            </td>
            <td><%= order.total_payment.to_s(:delimited) %>円</td>
            <td><%#= order.order_status_i18n %></td>
            <td><%= link_to '表示する',order_path(order),class:"btn btn-primary" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

     <div class="row">
      <div class="col-md-3 mx-auto">
        <nav aria-label="Page navigation example">
        <% paginate @orders %>
        </nav>
      </div>
     </div>


  </div>
</main>

app/views/customer/orders/logs.html.erb
<div class="container">
  <div class="row-justify-content-center">
    <div class="col-4 p-5 text-center">
    <h3><b>注文情報確認</b></h3>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-8 p-4 text-left">
      <table class="tabele table-bordered">
        <thead>
          <tr class="table-secondary">
            <th class="col-4">商品名</th>
            <th class="col-2">単価(税込)</th>
            <th class="col-1">数量</th>
            <th class="col-1">小計</th>
          </tr>
        </thead>
        <tbody class="bg-light">
          <% @cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= image_tag cart_item.item.image, size: "80x50" %>
              <%= cart_item.item.name %>
            </td>
            <td><%= (cart_item.item.tax_out_price*1.1).to_i %></td>
            <td><%= cart_item.quantity %></td>
            <td>
              <% subtotal = ((cart_item.item.tax_out_price*cart_item.quantity)*1.1).to_i %>
              <%= subtotal %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>


    <div class="col-4 p-4">
      <table class="table table-bordered bg-light">
        <tbody>
          <tr>
            <th>送料</th>
            <td><%= @postage %></td>
          </tr>
          <tr>
            <th>商品合計</th>
            <td><%= @total_payment %></td>
          </tr>
          <tr>
            <th>請求金額</th>
            <td><%= @total_payment + @postage %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <h5><b>支払い方法</b></h5>
      <p>
        <%= @order.payment_method_i18n %>
      </p>
    </div>
  </div>

  <div class="row">
      <div class="col-md-2">
        <h5><b>お届け先</b></h5>
        <p>
          〒
          <%= @order.postal_code %>
          <%= @order.address %>
          <%= @order.name %>
        </p>
      </div>
    </div>
  </div>

  <div class="row justify-content-center ">
    <div class="col-1">
        <%= form_with model: @order, url:orders_path, local: true do |f| %>
          <%= f.hidden_field :payment_method, value: @order.payment_method %>
          <%= f.hidden_field :postal_code, value: @order.postal_code %>
          <%= f.hidden_field :address, value: @order.address %>
          <%= f.hidden_field :name, value: @order.name %>
          <%= f.hidden_field :postage, value: @postage %>
          <%= f.hidden_field :total_payment, value: @order.total_payment %>
          <%= f.submit "注文を確定する", class: "btn btn-sm btn-success" %>
        <% end %>
    </div>
  </div>
</div>

app/views/customer/orders/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h5 class="offset-sm-2 " style="background-color: #eeeeee; display: inline-block; padding:0 20px; font-weight: bold; margin-top: 50px; margin-bottom: 50px;"> 注文情報入力 </h5>
        <%= form_with model: @order, url: logs_orders_path, method: :post, local: true do |f| %>

            <h5 style="font-weight: bold;">支払い方法</h5>

            <div style="margin-left: 30px;">
            <%= f.radio_button :payment_method, Order.payment_methods.key(0) %><%= f.label :payment_method, Order.payment_methods_i18n[:credit_card]%>
            </div>


            <div style="margin-left: 30px;">
            <%= f.radio_button :payment_method, Order.payment_methods.key(1) %>
            <%= f.label :payment_method, Order.payment_methods_i18n[:transfer]%>
            </div>


            <h5 style="font-weight: bold;">お届け先</h5>
            <div style="margin-left: 30px;"><%= f.radio_button :address_number, 1, checked: true %>
            <%= f.label :address_number_1, "ご自身の住所" %></div>
             <div style="margin-left: 60px;">〒<%= "#{current_customer.postal_code} #{current_customer.address}" %></div>
             <div style="margin-left: 60px;"><%= current_customer.family_name %><%= current_customer.first_name %></div>

            <div style="margin-left: 30px;"><%= f.radio_button :address_number, 2 %>
            <%= f.label :address_number_2, "登録済み住所から選択" %></div>
            <div style="margin-left: 60px;"><%= f.collection_select(:registered, @shipping_addresses.all, :id, :address, prompt: "選択してください") %></div>

            <div style="margin-left: 30px;"><%= f.radio_button :address_number, 3 %>
            <%= f.label :address_number_3, "新しいお届け先" %></div>
            <div style="margin-left: 60px;"><%= f.label :postal_code, "郵便番号（ハイフンなし）" %>
            <%= f.text_field :postal_code, :placeholder => "0000000" %></div>
            <div style="margin-left: 60px;"><%= f.label :address, "住所" %>
            <%= f.text_field :address, :size=>"60x0", :placeholder => "東京都渋谷区代々木神園町0-0" %></div>
            <div style="margin-left: 60px;"><%= f.label :name, "宛名" %>
            <%= f.text_field :name, :placeholder => "令和道子" %><div>

            <div style="margin-left: 35%; margin-bottom: 10px; margin-top: 10px;"><%= f.submit "確認画面へ進む", class: "btn btn-success" %></div>
        <% end %>
    </div>
  </div>
</div>

app/views/customer/orders/show.html.erb
<main>
   <div class="container">
     <div class="row pt-4 mb-4">
       <h4>注文履歴詳細</h4>
     </div>

     <div class="row">
       <div class="col-md-7">
        <h5>注文情報</h5>
        <table class="table table-bordered bg-light">
          <tr>
            <th class="background-color">注文日</th>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <th class="background-color">配送先</th>
            <td>
              〒<%= @order.postal_code %></br>
              <%= @order.address %>
              <%= @order.name %>
              </td>
          </tr>
          <tr>
            <th class="background-color">支払い方法</th>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <th class="background-color">ステータス</th>
            <td><%#= @order.order_status_i18n %></td>
          </tr>
        </table>
      </div>

      <div class="col-md-5">
        <h5>請求情報</h5>
        <table class="table table-bordered bg-light">
          <tr>
            <th class="background-color">商品合計</th>
            <td><%= @total_payment %></td>
          </tr>
          <tr>
            <th class="background-color">配送料</th>
            <td><%= @postage %></td>
          </tr>
          <tr>
            <th class="background-color">ご請求額</th>
            <td><%= @total_payment + @postage %></td>
          </tr>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-md-10 mt-5">
        <h5>注文内容</h5>
        <table class="table table-bordered bg-light">
            <th class="background-color">商品</th>
            <th class="background-color">単価（税込）</th>
            <th class="background-color">個数</th>
            <th class="background-color">小計</th>
          </tr>
          <% @order.order_items.each do |order_items| %>
          <tr>
            <td><%= order_items.item.name %></td>
            <td><%= (order_items.item.tax_out_price*1.1).to_i %></td>
            <td><%= order_items.quantity %></td>
            <td>
              <% subtotal = ((order_items.item.tax_out_price*order_items.quantity)*1.1).to_i %>
              <%= subtotal %>
            </td>
           <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/customer/orders/thanx.html.erb
<h1>ご注文ありがとうございました！</h1>