config/routes.rb
Rails.application.routes.draw do

  root to: 'customer/homes#top'
   get '/about' => 'customer/homes#about'


  devise_for :admin, skip: [:registrations, :passwords],controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords],  controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }

  #管理者側のルートはurlにadminがつく
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :items
    resources :cart_items
  end

  #顧客側のルートはurlにcustomerがつかない
  scope module: :customer do
    resources :customers, only: [:show, :edit, :update] do
      collection do
        patch 'delete'
        get 'confirm_delete'
      end
    end
    resources :shipping_addresses, only: [:index, :edit ,:create, :update, :destroy]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :destroy, :update] do
      collection do
        delete :destroy_all
      end
    end
    resources :order_items
    resources :orders do
       collection do
         post :logs
         get :thanx
       end
     end

  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page]).reverse_order
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      @customer.update(status: false)
      flash[:notice] = "You have updated successfully."
      redirect_to admin_customer_path(@customer)
    else
      render "edit"
    end
  end
  

  
  private

  def customer_params
    params.require(:customer).permit(:family_name, :first_name, :kana_family_name, :kana_first_name, :postal_code, :address, :tel, :email)
  end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  def index
    @cart_items = my_cart
    @total_price = 0
    @total = @cart_items.sum{|cart_item|cart_item.item.tax_out_price.to_i * cart_item.quantity.to_i * 1.1}
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    if my_cart.find_by(item_id: params[:cart_item][:item_id]).present?
			item_in_cart = my_cart.find_by(item_id: params[:cart_item][:item_id])
			item_in_cart.quantity += params[:cart_item][:quantity].to_i
			item_in_cart.save
      flash[:notice] = '商品を追加でカートに入れました。'
      redirect_to cart_items_path
    elsif @cart_item.save
      flash[:notice] = '商品をカートに入れました。'
      redirect_to cart_items_path
    else
      flash[:alert] = '商品の追加に失敗しました。'
      redirect_to item_path(params[:item_id])
    ender_cart_items_path

    end

  end


  def update
    @cart_item = my_cart.find_by(id: params[:id])

    if @cart_item.update(quantity: params[:quantity].to_i)
      flash[:notice] = 'カート内の内容が更新されました'
    else
      flash[:alert] = 'カート内の内容の更新に失敗しました'
    end
    redirect_to request.referer
  end






def destroy

   #@cart_item = CartItem.find(params[:id])

    @cart_item = my_cart.find_by(id: params[:id])

    if @cart_item.destroy
      flash[:notice] = 'カート内の内容が削除されました'
    else
      flash[:alert] = 'カート内の内容の削除に失敗しました'
    end
    redirect_to request.referer

  end

  def destroy_all
    @cart_item = current_customer.cart_items
    @cart_item.destroy_all
    redirect_to cart_items_path
  end


  private

  def my_cart
    current_customer.cart_items
  end

  def cart_item_params
    params.require(:cart_item).permit(:item_id, :quantity)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!

  def edit
    @customer = Customer.find(params[:id])
  end

  def show
     @customer = Customer.find(params[:id])
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customer_path
    else
      render "edit"
    end
  end
  
  def delete
    @customer = current_customer
    @customer.update(status: false)
    reset_session
    flash[:notice] = "Thanyou for using this site ！"
    redirect_to root_path
  end
  
  def confirm_delete
    @customer = current_customer
  end


  private

  def customer_params
    params.require(:customer).permit(:family_name, :first_name, :kana_family_name, :kana_first_name, :postal_code, :address, :tel, :email, :status)
  end

end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController


  def top
    @items = Item.order(created_at: :desc).limit(4)
    
    
  end

  def about
  end
  
  private

  def home_params
    params.require(:home).permit(:name, :tax_out_price, :image)
  end
  
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    #カートに追加するため
    @cart_items = CartItem.new
  end


  private

  def item_params
    params.require(:item).permit(:name, :explanation, :tax_out_price, :image)
  end

end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  # def new
  #   if CartItem.exists?(customer_id: current_customer.id)
  #     @order = Order.new
  #   else
  #     redirect_to items_path
  #   end
  # end

    def new
    @cart = CartItem.all.where(customer: current_customer)
      if @cart.empty?
      redirect_to cart_items_path, notice: 'cart is empty.'
      end

    @order = Order.new
    @shipping_addresses = ShippingAddress.where(customer: current_customer)
    end



  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @order.save

    current_customer.cart_items.each do |cart_item|
      @order_items = OrderItem.new
      @order_items.item_id = cart_item.item_id

      #購入時価格
      @order_items.subprice = cart_item.item.tax_out_price
      @order_items.quantity = cart_item.quantity
      @order_items.order_id = @order.id
      @order_items.save
    end
    current_customer.cart_items.destroy_all
    redirect_to thanx_orders_path
  end

  def logs
    @cart_items = CartItem.all
    @customer = current_customer
    @total_payment = 0

    @cart_items.each do |cart_item|
    @total_payment += ((cart_item.item.tax_out_price * cart_item.quantity) * 1.1).floor
    end

    @order = Order.new(order_params)
    @postage = 600
    @order.total_payment = @total_payment + 600

    if params[:order][:address_number] == "1"
      @order.name = current_customer.family_name + current_customer.first_name
      @order.address = current_customer.address
      @order.postal_code = current_customer.postal_code

    elsif params[:order][:address_number] == "2"
      @address = ShippingAddress.find_by(customer_id: current_customer.id)
      @order.name = @address.name
      @order.address = @address.address
      @order.postal_code = @address.postal_code
    else params[:order][:select_address] = "3"
      @order.name = params[:order][:name]
      @order.address = params[:order][:address]
      @order.postal_code = params[:order][:postal_code]
    end
  end

  def index
    @orders = Order.order(created_at: :desc).page(params[:page]).per(8)
    # @orders = Order.all
    @order = current_customer
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @postage = 600
    @total_payment = 0
    @order_items.each do |order_items|
      @total_payment += ((order_items.item.tax_out_price*order_items.quantity)*1.1).floor
    end
  end

  def thanx
  end


  private

  def order_params
    params.require(:order).permit(:name, :postal_code, :payment_method, :total_payment, :address ,:customer_id, :postage)
  end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected

  def after_sign_in_path_for(resource)
    about_path(resource)
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :kana_family_name, :kana_first_name, :postal_code, :address, :tel])
  end

end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/shipping_addresses_controller.rb
class Customer::ShippingAddressesController < ApplicationController


  def index
    @shipping_address = current_customer.shipping_addresses.new
    @shipping_addresses = current_customer.shipping_addresses.all
  end

  def create
    @shipping_address = current_customer.shipping_addresses.new(shipping_address_params)
    if @shipping_address.save
      redirect_to shipping_addresses_path
    else
      @shipping_addresses = current_customer.shipping_addresses.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @shipping_address.update(shipping_address_params)
      redirect_to customers_shipping_addresses_path
    else
      render 'edit'
    end
  end

  def destroy
    @shipping_address = current_customer.shipping_addresses.find(params[:id])
    @shipping_address.destroy
    redirect_to shipping_addresses_path
  end

  private

  def set_address
    @shipping_address = current_customer.shipping_addresses.find(params[:id])
  end

  def shipping_address_params
    params.require(:shipping_address).permit(:name, :postal_code, :address).merge(customer_id: current_customer.id)
  end


end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="form-group" style="display: flex">
        <h5 class="table-active"><strong><%= @customer.family_name %><%= @customer.first_name %></strong>さんの会員情報編集</h5>
      </div>
      <%= form_with model: @customer, url: admin_customer_path, local:true do |f| %>
        <%= render "customer/shared/error_messages", resource: @customer %>
      <div class="form-group" style="display: flex">
        <div class="col-sm-3">会員ID</div>
        <div class="col-sm-3"><%= @customer.id %></div>
      </div>
      <div class="form-group" style="display: flex">
        <div class="col-sm-3">氏名</div>
        <div class="col-sm-3"><%= f.text_field :family_name %></div>
        <div class="col-sm-3"><%= f.text_field :first_name %></div>
      </div>
      <div class="form-group" style="display: flex">
        <div class="col-sm-3">フリガナ</div>
        <div class="col-sm-3"><%= f.text_field :kana_family_name %></div>
        <div class="col-sm-3"><%= f.text_field :kana_first_name %></div>
      </div>
      <div class="form-group" style="display: flex">
        <div class="col-sm-3"><%= f.label :postal_code, "郵便番号（ハイフンなし）" %></div>
        <div class="col-sm-3"><%= f.text_field :postal_code %></div>
      </div>
      <div class="form-group" style="display: flex">
        <div class="col-sm-3"><%= f.label :address, "住所" %></div>
        <div class="col-sm-7"><%= f.text_field :address, :size=>"58" %></div>
      </div>
      <div class="form-group" style="display: flex">
        <div class="col-sm-3"><%= f.label :tel, "電話番号（ハイフンなし）" %></div>
        <div class="col-sm-3"><%= f.text_field :tel %></div>
      </div>
      <div class="form-group" style="display: flex">
        <div class="col-sm-3"><%= f.label :email, "メールアドレス" %></div>
        <div class="col-sm-3"><%= f.email_field :email, autofocus: true, autocomplete: "email" %></div>
      </div>
      <div class="form-group" style="display: flex">
          <div class="col-sm-3">会員ステータス</div>
          <div class="col-sm-3">
            <%= f.radio_button :status, :false, checked: true  %>
            <%= f.label :status, "有効", {value: :false, style: "display: inline-block;"} %>
            <%= f.radio_button :status, :ture %>
            <%= f.label :status, "退会", {value: :true, style: "display: inline-block;"} %>
          </div>
        </div>
      <div class="col-sm-4 offset-sm-3"><%= f.submit "変更を保存", class: "btn btn-success" %></div>

      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row justify-content-center mt-4">
    <div class="col-10 row justify-content-between">
      <h4>会員一覧</h4>
      <table class="table">
        <thead>
          <tr class="table-active">
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to admin_customer_path(customer) do %>
                  <%= customer.family_name %><%= customer.first_name %>
                <% end %>
              </td>
              <td><%= customer.email %></td>
              <% if customer.status == true %>
                <td style="color: #00cc00; font-weight: bold;">有効</td>
              <% else %>
                <td style="color: #cccccc; font-weight: bold;">退会</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="form-group" style="display: flex">
        <h5 class="table-active"><%= @customer.family_name %><%= @customer.first_name %>さんの会員詳細</h5>
      </div>
      <table class="table">
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.family_name %> <%= @customer.first_name %></td>
        </tr>
        <tr>
          <td>カナ</td>
          <td><%= @customer.kana_family_name %> <%= @customer.kana_first_name %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%=@customer.postal_code %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%=@customer.tel %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <% if @customer.status == true %>
            <td style="color: #00cc00; font-weight: bold;">有効</td>
          <% else %>
            <td style="color: #cccccc; font-weight: bold;">退会</td>
          <% end %>
        </tr>
      </table>
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
      <%= link_to "注文履歴一覧を見る", admin_orders_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>